### ISSUE TITLE
More guidance needed on questions

### ISSUE THREAD

**Issue by marioa** [softwaresaved/common-form-questions#15]
Not clear to me what we are saying about these questions - are these a MUST? a SHOULD? i.e. we MUST use all of these questions? SHOULD we be using all of these questions for an event? Some of them are clearly a MAY, e.g. the telephone number may be used for some instances but if we want to have a degree of uniformity we should perhaps use the [REFC2199](https://www.ietf.org/rfc/rfc2119.txt) nomenclature.

**Comment by shoaibsufi** [comment]
So we have decided:

Common form questions are there to suggest what might go into a survey

It's for the person putting it together to justify what is needed in their case.

So ticket closed.
